In [1]:

from statsbombpy import sb 
import pandas as pd

def get_shot_data(competition_id = 43 , season_id = 3):
    matches = sb.matches(competition_id = competition_id, season_id = season_id)

    all_shots = []
    for match_id in matches['match_id']:
        events = sb.events(match_id = match_id)
        shots = events[events['type']=='Shot'].copy()
        all_shots.append(shots)
    return pd.concat(all_shots)

df = get_shot_data()
df[['x','y']] = pd.DataFrame(df['location'].tolist(),index = df.index)
print(f"Loaded {len(df)} shots for analysis.")

c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\LENOVO\Desktop\gauravmalik\MachineLearning\machineLearningEnvironment\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Loaded 1706 shots for analysis.

In [2]:
df[['x','y']]

          x     y
3817  115.0  18.0
3818  112.0  54.0
3819   98.0  37.0
3820  119.0  36.0
3821   97.0  56.0
...     ...   ...
3637  102.0  22.0
3638   95.0  30.0
3639  116.0  30.0
3640  101.0  58.0
3641  116.0  53.0

[1706 rows x 2 columns]

In [3]:
df

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,counterpress,dribble_nutmeg,...,pass_cut_back,pass_technique,pass_through_ball,shot_one_on_one,ball_recovery_offensive,miscontrol_aerial_won,pass_miscommunication,shot_redirect,x,y
3817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.0,18.0
3818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.0,54.0
3819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.0,37.0
3820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.0,36.0
3821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0,56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.0,22.0
3638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.0,30.0
3639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.0,30.0
3640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.0,58.0
3641,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.0,53.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1706 entries, 3817 to 3641
Data columns (total 97 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   50_50                           0 non-null      object
 1   bad_behaviour_card              0 non-null      object
 2   ball_receipt_outcome            0 non-null      object
 3   ball_recovery_recovery_failure  0 non-null      object
 4   block_deflection                0 non-null      object
 5   block_offensive                 0 non-null      object
 6   carry_end_location              0 non-null      object
 7   clearance_aerial_won            0 non-null      object
 8   counterpress                    0 non-null      object
 9   dribble_nutmeg                  0 non-null      object
 10  dribble_outcome                 0 non-null      object
 11  duel_outcome                    0 non-null      object
 12  duel_type                       0 non-null      object
 13  duration                        1706 non-null   float64
 14  foul_committed_advantage        0 non-null      object
 15  foul_committed_card             0 non-null      object
 16  foul_committed_penalty          0 non-null      object
 17  foul_committed_type             0 non-null      object
 18  foul_won_advantage              0 non-null      object
 19  foul_won_defensive              0 non-null      object
 20  foul_won_penalty                0 non-null      object
 21  goalkeeper_body_part            0 non-null      object
 22  goalkeeper_end_location         0 non-null      object
 23  goalkeeper_outcome              0 non-null      object
 24  goalkeeper_position             0 non-null      object
 25  goalkeeper_technique            0 non-null      object
 26  goalkeeper_type                 0 non-null      object
 27  id                              1706 non-null   object
 28  index                           1706 non-null   int64
 29  interception_outcome            0 non-null      object
 30  location                        1706 non-null   object
 31  match_id                        1706 non-null   int64
 32  minute                          1706 non-null   int64
 33  pass_aerial_won                 0 non-null      object
 34  pass_angle                      0 non-null      float64
 35  pass_assisted_shot_id           0 non-null      object
 36  pass_backheel                   0 non-null      object
 37  pass_body_part                  0 non-null      object
 38  pass_cross                      0 non-null      object
 39  pass_deflected                  0 non-null      object
 40  pass_end_location               0 non-null      object
 41  pass_goal_assist                0 non-null      object
 42  pass_height                     0 non-null      object
 43  pass_length                     0 non-null      float64
 44  pass_outcome                    0 non-null      object
 45  pass_recipient                  0 non-null      object
 46  pass_recipient_id               0 non-null      float64
 47  pass_shot_assist                0 non-null      object
 48  pass_switch                     0 non-null      object
 49  pass_type                       0 non-null      object
 50  period                          1706 non-null   int64
 51  play_pattern                    1706 non-null   object
 52  player                          1706 non-null   object
 53  player_id                       1706 non-null   float64
 54  position                        1706 non-null   object
 55  possession                      1706 non-null   int64
 56  possession_team                 1706 non-null   object
 57  possession_team_id              1706 non-null   int64
 58  related_events                  1706 non-null   object
 59  second                          1706 non-null   int64
 60  shot_aerial_won                 124 non-null    object
 61  shot_body_part                  1706 non-null   object
 62  shot_deflected                  17 non-null     object
 63  shot_end_location               1706 non-null   object
 64  shot_first_time                 357 non-null    object
 65  shot_follows_dribble            2 non-null      object
 66  shot_freeze_frame               1638 non-null   object
 67  shot_key_pass_id                1180 non-null   object
 68  shot_open_goal                  17 non-null     object
 69  shot_outcome                    1706 non-null   object
 70  shot_statsbomb_xg               1706 non-null   float64
 71  shot_technique                  1706 non-null   object
 72  shot_type                       1706 non-null   object
 73  substitution_outcome            0 non-null      object
 74  substitution_outcome_id         0 non-null      float64
 75  substitution_replacement        0 non-null      object
 76  substitution_replacement_id     0 non-null      float64
 77  tactics                         0 non-null      object
 78  team                            1706 non-null   object
 79  team_id                         1706 non-null   int64
 80  timestamp                       1706 non-null   object
 81  type                            1706 non-null   object
 82  under_pressure                  329 non-null    object
 83  block_save_block                0 non-null      object
 84  dribble_overrun                 0 non-null      object
 85  foul_committed_offensive        0 non-null      object
 86  injury_stoppage_in_chain        0 non-null      object
 87  pass_cut_back                   0 non-null      object
 88  pass_technique                  0 non-null      object
 89  pass_through_ball               0 non-null      object
 90  shot_one_on_one                 55 non-null     object
 91  ball_recovery_offensive         0 non-null      object
 92  miscontrol_aerial_won           0 non-null      object
 93  pass_miscommunication           0 non-null      object
 94  shot_redirect                   6 non-null      object
 95  x                               1706 non-null   float64
 96  y                               1706 non-null   float64
dtypes: float64(10), int64(8), object(79)
memory usage: 1.3+ MB

In [5]:
import numpy as np
df['distance_from_goal'] = np.sqrt((120-df['x'])**2 + (40-df['y'])**2)
print(df[['x','y','distance_from_goal']].head())

          x     y  distance_from_goal
3817  115.0  18.0           22.561028
3818  112.0  54.0           16.124515
3819   98.0  37.0           22.203603
3820  119.0  36.0            4.123106
3821   97.0  56.0           28.017851

In [6]:
import numpy as np
goal_width = 8
left_post_y = 36
right_post_y = 44

d1 = np.sqrt((120-df['x'])**2 + (left_post_y-df['y'])**2)
d2 = np.sqrt((120-df['x'])**2 + (right_post_y-df['y'])**2)

cos_theta = (d1**2  + d2**2  - goal_width**2) / (2*d1*d2)

# clipping so that the anlge remaining the range of arccos i.e. cos inverse as it's range is between -1 to 1, and due to decimal arithmatic being error prone a value such as 1.0000000000002 may crash the code

cos_theta = np.clip(cos_theta,-1.0,1)


df['shot_angle'] = np.degrees(np.arccos(cos_theta))
print(df[['distance_from_goal','shot_angle']].head())

      distance_from_goal  shot_angle
3817           22.561028    4.638584
3818           16.124515   14.697319
3819           22.203603   20.252686
3820            4.123106   82.874984
3821           28.017851   13.456275

In [7]:
# statsbomb stores it body part data as a dictionary such as {'id':40,'name':'Right Foot'}

df_encoded = pd.get_dummies(df,columns = ['shot_body_part'],prefix="shot_type")
# print(df_encoded.columns)


print(df_encoded[['distance_from_goal','shot_angle','shot_type_Head','shot_type_Right Foot','shot_type_Left Foot']].head())

      distance_from_goal  shot_angle  shot_type_Head  shot_type_Right Foot  \
3817           22.561028    4.638584           False                  True
3818           16.124515   14.697319           False                  True
3819           22.203603   20.252686           False                  True
3820            4.123106   82.874984            True                 False
3821           28.017851   13.456275           False                  True

      shot_type_Left Foot
3817                False
3818                False
3819                False
3820                False
3821                False

In [8]:
df['shot_type'].value_counts()

shot_type
Open Play    1556
Free Kick      82
Penalty        68
Name: count, dtype: int64

In [9]:
df['shot_body_part'].value_counts()

shot_body_part
Right Foot    882
Left Foot     500
Head          310
Other          14
Name: count, dtype: int64

In [10]:
df['shot_outcome'].value_counts()

shot_outcome
Off T      572
Blocked    457
Saved      341
Goal       183
Wayward    129
Post        24
Name: count, dtype: int64

In [12]:
df_encoded['is_goal'] = np.where(df['shot_outcome']=='Goal',1,0)
print(df_encoded['is_goal'].value_counts(normalize =True)*100)

is_goal
0    89.273154
1    10.726846
Name: proportion, dtype: float64

In [13]:
from sklearn.metrics import brier_score_loss , log_loss, roc_auc_score

def evaluate_xg_model(y_true,y_pred_proba):
    """
    Evaluates an xG model's probabilistic predictions.
    y_true = actual binary outcome(0 or 1).
    y_pred_proba : predicted probabilities (0.0 to 1.0)
    """
    brier = brier_score_loss(y_true,y_pred_proba)
    # Log loss requires careful handling of absolute of 0s and 1s, which sklearn handles safely
    ll = log_loss(y_true , y_pred_proba)

    ## ROC-AUC tells us how well the model ranks shots
    # E.g. does a 0.8 xG shot genuinely look better than a 0.2 xG shot?
    auc = roc_auc_score(y_true , y_pred_proba)
    print(f"--- xG Model Evaluation ---")
    print(f"Brier Score: {brier:.4f} (Closer to 0 is better)")
    print(f"Log Loss:    {ll:.4f} (Closer to 0 is better)")
    print(f"ROC-AUC:     {auc:.4f} (Closer to 1.0 is better)")
    return brier,ll,auc
# example usage : 
y_true = np.array([0,0,1,0,1])
y_pred = np.array([0.05,0.12,0.88,0.30,0.15])
evaluate_xg_model(y_true,y_pred)

--- xG Model Evaluation ---
Brier Score: 0.1688 (Closer to 0 is better)
Log Loss:    0.5122 (Closer to 0 is better)
ROC-AUC:     0.8333 (Closer to 1.0 is better)

(0.16875999999999997, 0.5121509932463868, 0.8333333333333334)

In [14]:
# Building a baseline logistic regression model
from sklearn.linear_model import LogisticRegression
features = ['distance_from_goal','shot_angle','shot_type_Right Foot','shot_type_Head','shot_type_Left Foot']
X = df_encoded[features]
y = df_encoded['is_goal']

In [15]:
lr_model = LogisticRegression(solver='liblinear',max_iter=1000)
lr_model.fit(X,y)

LogisticRegression(max_iter=1000, solver='liblinear')

In [16]:
df_encoded['baseline_xG'] = lr_model.predict_proba(X)[:,1]
df_encoded.to_csv("shots_data_refactored")

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,stratify=y,random_state=42
    )

In [18]:
print(f"Training_set : {len(X_train)} shots. Goal Ratio : {y_train.mean():.3f}")
print(f"Testing set: {len(X_test)} shots. Goal Ratio: {y_test.mean():.3f}")

Training_set : 1364 shots. Goal Ratio : 0.107
Testing set: 342 shots. Goal Ratio: 0.108

In [19]:
startified_model = LogisticRegression(solver='liblinear' , max_iter = 1000)
startified_model.fit(X_train,y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [20]:
y_pred_proba_stratified = startified_model.predict_proba(X_test)[:,-1]

In [21]:
evaluate_xg_model(y_test,y_pred_proba_stratified)

--- xG Model Evaluation ---
Brier Score: 0.0827 (Closer to 0 is better)
Log Loss:    0.2879 (Closer to 0 is better)
ROC-AUC:     0.7840 (Closer to 1.0 is better)

(0.0827088083920387, 0.2879095800363386, 0.7839610101905183)

- A linear model sees a negative weight for distance and applies it uniformly. It says: "If 10 meters is good, 5 meters is better, and 60 meters is basically impossible." It cannot easily account for the fact that a world-class striker might have a specific "sweet spot" at 25 yards where they are actually quite dangerous.

### Looking at the weights learned by the model

In [22]:
weights = pd.DataFrame({
    'feature' : features,
    'Weight' : startified_model.coef_[0]
})
print(weights.sort_values(by='Weight',ascending=False))

                feature    Weight
2  shot_type_Right Foot  0.736644
4   shot_type_Left Foot  0.343664
1            shot_angle  0.020706
0    distance_from_goal -0.124419
3        shot_type_Head -0.928872